classdef node < handle
    %UNTITLED7 Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        parent = node.empty;
        children = {};
        net;
        fine_labels;
        filePath;
        id = 1;
        labelsTransform;
        opts=struct('expDir'	,	'../output/trial', ...
			'batchSize'     ,	50, ...
			'numEpochs'     ,	1, ...
			'learningRate'	,	2, ...
			'momentum'      ,	0,  ...
			'weightDecay'	,	0, ...
			'saveMomentum'	,	true, ...
			'randomSeed'	,	0,  ...
			'backPropDepth'	,	+inf,  ...
			'errorFunction'	,	'multiclass',  ...
			'continue'  	,	true, ...
			'conserveMemory',	true, ...
			'networkType'  	,	'simplenn',  ...
			'train'         ,	[], ...
			'val'           ,	[], ...
			'errorLabels'   ,	{{}},  ...
			'plotDiagnostics',	false,  ...
			'plotStatistics',	false, ...
			'profile'       ,	true,  ...
			'flip'          ,	false, ...
			'gpus'          , 	[], ...
			'epochSize'     ,	inf, ...
			'prefetch'      ,       true, ... 
			'solver'        ,	[], ...
			'numSubBatches'	,	1, ...
			'saveSolverState',	true, ...
			'nesterovUpdate',	false, ...
			'parameterServer', struct('method','mmap','prefix','mcn'), ...
			'memoryMapFile'	,	fullfile(tempdir, 'matconvnet.bin'), ...
			'sync'		,	true, ...
			'cudnn'		,	true, ...
			'postEpochFn'	,	[] );
    
    end
    
    methods
        function addNode(P,child)
            n = numel(P.children);
            child.id = P.id*100 + n + 1;
            child.parent = P;
            P.children{1,n+1} = child;
        end
            
            

    end
end